import assert from "node:assert/strict";
import { inflateRawSync } from "node:zlib";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import type {
  Card,
  CardPoolProfile,
  CardPoolStatus,
  CardStatRow,
  CardStrategyProfile,
  CardTranslation,
  CardType
} from "../src/features/draft/index.ts";

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
export const WOONGI_SOURCE_REF = "woongi-tierlist-2025-09-01";
export const WOONGI_STATS_SNAPSHOT_ID = "woongi-lumin-bga-2025-09-01";
export const WOONGI_CARD_POOL_PROFILE_ID = "bga-arena-woongi-2025-09-01";
const importDate = "2026-05-09";

const defaultInputPath = "data/raw/woongi-tierlist-2025-09-01.xlsx";
const cardsPath = "data/normalized/cards.json";
const translationsPath = "data/normalized/translations.ko-KR.json";
const strategyProfilesPath = "data/manual/card-strategy-profiles.json";
const statsOutputPath = "data/normalized/stats.woongi-lumin-bga.2025-09-01.json";
const cardPoolOutputPath = "data/normalized/card-pool.bga-arena.woongi-2025-09-01.json";
const mapOutputPath = "data/manual/card-id-map.woongi.2025-09-01.review.json";

type CellValue = string | number;
type SheetRow = Record<number, CellValue>;

type WoongiRow = {
  sourceSheet: "occupations" | "improvements";
  sourceRow: number;
  sourceNumber: number;
  cardType: CardType;
  arenaName: string;
  officialName: string;
  effectText: string;
  costRaw?: string;
  tier: string;
  wtdPwr?: number;
  cardId: string;
  mappingStatus: "matched_existing" | "auto_generated";
};

type CardIdMapQueue = {
  sourceRef: string;
  snapshotId: string;
  generatedAt: string;
  rawFile: string;
  summary: {
    totalRows: number;
    matchedExisting: number;
    autoGenerated: number;
  };
  rows: Array<{
    cardId: string;
    mappingStatus: WoongiRow["mappingStatus"];
    cardType: CardType;
    sourceSheet: WoongiRow["sourceSheet"];
    sourceRow: number;
    sourceNumber: number;
    arenaName: string;
    officialName: string;
    tier: string;
    wtdPwr?: number;
  }>;
};

type ImportOutputs = {
  rows: WoongiRow[];
  cards: Card[];
  translations: CardTranslation[];
  stats: CardStatRow[];
  cardPoolProfile: CardPoolProfile;
  cardIdMapQueue: CardIdMapQueue;
  strategyProfiles: CardStrategyProfile[];
};

type CliOptions = {
  write: boolean;
  inputPath: string;
};

if (isMainModule()) {
  const options = parseCliOptions(process.argv.slice(2));
  const outputs = await buildWoongiImport(options.inputPath);

  if (options.write) {
    await writeJson(cardsPath, outputs.cards);
    await writeJson(translationsPath, outputs.translations);
    await writeJson(statsOutputPath, outputs.stats);
    await writeJson(cardPoolOutputPath, outputs.cardPoolProfile);
    await writeJson(mapOutputPath, outputs.cardIdMapQueue);
    await writeJson(strategyProfilesPath, outputs.strategyProfiles);
  }

  console.log(
    [
      `Woongi import parsed ${outputs.rows.length} cards.`,
      `stats=${outputs.stats.length}`,
      `cards=${outputs.cards.length}`,
      `translations=${outputs.translations.length}`,
      `strategyProfiles=${outputs.strategyProfiles.length}`,
      options.write ? "wrote normalized outputs." : "dry run only."
    ].join(" ")
  );
}

export async function buildWoongiImport(inputPath = defaultInputPath): Promise<ImportOutputs> {
  const absoluteInputPath = resolveWorkspacePath(inputPath);
  const entries = parseZipEntries(await readFile(absoluteInputPath));
  const sharedStrings = parseSharedStrings(readZipText(entries, "xl/sharedStrings.xml"));
  const occupationRows = parseOccupationRows(readWorksheet(entries, sharedStrings, "xl/worksheets/sheet2.xml"));
  const improvementRows = parseImprovementRows(readWorksheet(entries, sharedStrings, "xl/worksheets/sheet3.xml"));
  const sourceRows = [...occupationRows, ...improvementRows];

  const existingCards = await readJsonIfExists<Card[]>(cardsPath, []);
  const existingTranslations = await readJsonIfExists<CardTranslation[]>(translationsPath, []);
  const existingProfiles = await readJsonIfExists<CardStrategyProfile[]>(strategyProfilesPath, []);
  const existingCardIdMapQueue = await readJsonIfExists<CardIdMapQueue | null>(mapOutputPath, null);
  const existingNameIndex = buildExistingNameIndex(existingTranslations);
  const existingCardIds = new Set(existingCards.map((card) => card.id));
  const previousRowMappings = buildPreviousRowMappingIndex(existingCardIdMapQueue);
  const rows: WoongiRow[] = sourceRows.map((row): WoongiRow => {
    const proposedId = proposedCardId(row.cardType, row.sourceNumber);
    const priorCardId = previousRowMappings.get(rowKey(row));
    const usablePriorCardId =
      priorCardId !== undefined && (!isGeneratedWoongiId(priorCardId) || priorCardId === proposedId)
        ? priorCardId
        : undefined;
    const nameMatchedCardId =
      existingNameIndex.get(normalizeName(row.officialName)) ??
      existingNameIndex.get(normalizeName(row.arenaName));
    const existingCardId = usablePriorCardId ?? (existingCardIds.has(proposedId) ? proposedId : nameMatchedCardId);
    const cardId = existingCardId ?? proposedId;

    return {
      ...row,
      cardId,
      mappingStatus: isGeneratedWoongiId(cardId) ? "auto_generated" : "matched_existing"
    };
  });

  const cards = mergeCards(existingCards, rows);
  const translations = mergeTranslations(existingTranslations, rows);
  const stats = buildStats(rows);
  const cardPoolProfile = buildCardPoolProfile(rows);
  const cardIdMapQueue = buildCardIdMapQueue(rows, inputPath);
  const strategyProfiles = mergeStrategyProfiles(existingProfiles, rows);

  return {
    rows,
    cards,
    translations,
    stats,
    cardPoolProfile,
    cardIdMapQueue,
    strategyProfiles
  };
}

function parseOccupationRows(rows: Array<{ rowNumber: number; cells: SheetRow }>): Omit<WoongiRow, "cardId" | "mappingStatus">[] {
  return rows.flatMap(({ rowNumber, cells }) => {
    if (rowNumber === 1) return [];

    const sourceNumber = toInteger(cells[1]);
    const arenaName = normalizeCellText(cells[2]);
    const officialName = normalizeCellText(cells[3]) || arenaName;
    const wtdPwr = toNumber(cells[6]);
    if (sourceNumber === undefined || arenaName === "") return [];

    return [
      {
        sourceSheet: "occupations",
        sourceRow: rowNumber,
        sourceNumber,
        cardType: "occupation",
        arenaName,
        officialName,
        effectText: normalizeEffectText(cells[4]),
        tier: normalizeTier(cells[5]),
        ...(wtdPwr === undefined ? {} : { wtdPwr })
      }
    ];
  });
}

function parseImprovementRows(rows: Array<{ rowNumber: number; cells: SheetRow }>): Omit<WoongiRow, "cardId" | "mappingStatus">[] {
  return rows.flatMap(({ rowNumber, cells }) => {
    if (rowNumber === 1) return [];

    const sourceNumber = toInteger(cells[1]);
    const arenaName = normalizeCellText(cells[2]);
    const officialName = normalizeCellText(cells[3]) || arenaName;
    if (sourceNumber === undefined || arenaName === "") return [];

    const tier = normalizeTier(cells[6]);
    const costRaw = normalizeOptionalRaw(cells[5]);
    const wtdPwr = toNumber(cells[7]);
    return [
      {
        sourceSheet: "improvements",
        sourceRow: rowNumber,
        sourceNumber,
        cardType: tier === "주요 설비" ? "major_improvement" : "minor_improvement",
        arenaName,
        officialName,
        effectText: normalizeEffectText(cells[4]),
        ...(costRaw === undefined ? {} : { costRaw }),
        tier,
        ...(wtdPwr === undefined ? {} : { wtdPwr })
      }
    ];
  });
}

function mergeCards(existingCards: Card[], rows: WoongiRow[]): Card[] {
  const cardsById = new Map(existingCards.map((card) => [card.id, structuredClone(card)]));

  for (const row of rows) {
    const existing = cardsById.get(row.cardId);
    if (existing) {
      existing.sourceRefs = uniqueStrings([...existing.sourceRefs, WOONGI_SOURCE_REF]);
      existing.availability = {
        ...existing.availability,
        bga: isActiveTier(row.tier) || existing.availability.bga === true,
        physicalKo: true,
        revised: true
      };
      if (existing.costRaw === undefined && row.costRaw !== undefined) existing.costRaw = row.costRaw;
      existing.updatedAt = importDate;
      continue;
    }

    cardsById.set(row.cardId, {
      id: row.cardId,
      type: row.cardType,
      decks: [],
      editions: ["revised"],
      ...(row.costRaw === undefined ? {} : { costRaw: row.costRaw }),
      availability: {
        bga: isActiveTier(row.tier),
        physicalKo: true,
        revised: true
      },
      tagIds: [],
      timingTagIds: [],
      sourceRefs: [WOONGI_SOURCE_REF],
      createdAt: importDate,
      updatedAt: importDate
    });
  }

  return [...cardsById.values()].sort(compareCards);
}

function mergeTranslations(existingTranslations: CardTranslation[], rows: WoongiRow[]): CardTranslation[] {
  const translationsByCardId = new Map(existingTranslations.map((translation) => [
    translation.cardId,
    structuredClone(translation)
  ]));
  const aliasCandidateKeys = buildAliasCandidateKeys(rows);
  const ambiguousAliasKeys = buildAmbiguousAliasKeys(rows);

  for (const row of rows) {
    const existing = translationsByCardId.get(row.cardId);
    const aliases = rowAliases(row, ambiguousAliasKeys);

    if (existing) {
      existing.officialName ??= row.officialName;
      existing.bgaName ??= row.arenaName;
      existing.aliases = uniqueStrings([...cleanExistingAliases(existing.aliases, aliasCandidateKeys), ...aliases]);
      if (row.effectText !== "") existing.effectText = row.effectText;
      existing.shortText ??= summarizeEffect(row.effectText);
      existing.sourceRefs = uniqueStrings([...existing.sourceRefs, WOONGI_SOURCE_REF]);
      existing.updatedAt = importDate;
      continue;
    }

    translationsByCardId.set(row.cardId, {
      cardId: row.cardId,
      locale: "ko-KR",
      name: row.officialName,
      officialName: row.officialName,
      bgaName: row.arenaName,
      aliases,
      effectText: row.effectText,
      shortText: summarizeEffect(row.effectText),
      sourceRefs: [WOONGI_SOURCE_REF],
      updatedAt: importDate
    });
  }

  return [...translationsByCardId.values()].sort((left, right) => left.cardId.localeCompare(right.cardId));
}

function buildAmbiguousAliasKeys(rows: WoongiRow[]): Set<string> {
  const aliasCardIds = new Map<string, Set<string>>();

  for (const row of rows) {
    if (row.arenaName === row.officialName) continue;

    const key = normalizeName(row.arenaName);
    const cardIds = aliasCardIds.get(key) ?? new Set<string>();
    cardIds.add(row.cardId);
    aliasCardIds.set(key, cardIds);
  }

  return new Set(
    [...aliasCardIds.entries()]
      .filter(([, cardIds]) => cardIds.size > 1)
      .map(([key]) => key)
  );
}

function buildAliasCandidateKeys(rows: WoongiRow[]): Set<string> {
  return new Set(
    rows
      .filter((row) => row.arenaName !== row.officialName)
      .map((row) => normalizeName(row.arenaName))
  );
}

function rowAliases(row: WoongiRow, ambiguousAliasKeys: Set<string>): string[] {
  if (row.arenaName === row.officialName) return [];
  if (ambiguousAliasKeys.has(normalizeName(row.arenaName))) return [];
  return [row.arenaName];
}

function cleanExistingAliases(aliases: string[], aliasCandidateKeys: Set<string>): string[] {
  return aliases.filter((alias) => !aliasCandidateKeys.has(normalizeName(alias)));
}

function buildStats(rows: WoongiRow[]): CardStatRow[] {
  return rows.map((row) => ({
    snapshotId: WOONGI_STATS_SNAPSHOT_ID,
    cardId: row.cardId,
    rank: row.sourceNumber,
    ...(row.wtdPwr === undefined ? {} : { wtdPwr: row.wtdPwr }),
    tier: row.tier
  }));
}

function buildCardPoolProfile(rows: WoongiRow[]): CardPoolProfile {
  const cardStatuses: Record<string, CardPoolStatus> = {};
  for (const row of rows) {
    cardStatuses[row.cardId] = isActiveTier(row.tier) ? "active" : "inactive";
  }

  return {
    id: WOONGI_CARD_POOL_PROFILE_ID,
    name: "BGA Arena Woongi tierlist 2025-09-01",
    sourceRefs: [WOONGI_SOURCE_REF],
    collectedAt: "2025-09-01",
    playerCount: 4,
    cardStatuses,
    notes:
      "Derived from Woongi/bigman0603 tierlist based on Lumin BGA wtdPWR. Major improvements are included for lookup, not draft recommendation."
  };
}

function buildCardIdMapQueue(rows: WoongiRow[], inputPath: string): CardIdMapQueue {
  return {
    sourceRef: WOONGI_SOURCE_REF,
    snapshotId: WOONGI_STATS_SNAPSHOT_ID,
    generatedAt: importDate,
    rawFile: normalizePath(inputPath),
    summary: {
      totalRows: rows.length,
      matchedExisting: rows.filter((row) => row.mappingStatus === "matched_existing").length,
      autoGenerated: rows.filter((row) => row.mappingStatus === "auto_generated").length
    },
    rows: rows.map((row) => ({
      cardId: row.cardId,
      mappingStatus: row.mappingStatus,
      cardType: row.cardType,
      sourceSheet: row.sourceSheet,
      sourceRow: row.sourceRow,
      sourceNumber: row.sourceNumber,
      arenaName: row.arenaName,
      officialName: row.officialName,
      tier: row.tier,
      ...(row.wtdPwr === undefined ? {} : { wtdPwr: row.wtdPwr })
    }))
  };
}

function mergeStrategyProfiles(existingProfiles: CardStrategyProfile[], rows: WoongiRow[]): CardStrategyProfile[] {
  const profilesByCardId = new Map(existingProfiles.map((profile) => [profile.cardId, structuredClone(profile)]));
  const candidates = rows
    .filter((row) => row.cardType !== "major_improvement")
    .filter((row) => row.wtdPwr !== undefined)
    .sort((left, right) => (right.wtdPwr ?? 0) - (left.wtdPwr ?? 0))
    .slice(0, 24);

  for (const row of candidates) {
    if (profilesByCardId.has(row.cardId)) continue;

    const concreteRoles = inferConcreteRoles(row);
    const roles = uniqueStrings([
      ...(row.tier === "S" ? ["broken"] : []),
      ...(row.tier === "S" || row.tier === "1" ? ["plan_anchor"] : []),
      ...concreteRoles
    ]);
    const needs = inferNeeds(row, concreteRoles);

    profilesByCardId.set(row.cardId, {
      cardId: row.cardId,
      cardPoolProfileId: WOONGI_CARD_POOL_PROFILE_ID,
      arenaActive: isActiveTier(row.tier),
      roles,
      isBroken: row.tier === "S",
      isPlanAnchor: row.tier === "S" || row.tier === "1",
      solves: concreteRoles,
      increasesNeedFor: needs,
      saturationPenaltyTo: concreteRoles,
      synergyWith: [],
      conflictsWith: [],
      riskTags: ["needs_manual_strategy_review"],
      timingWindow: row.tier === "S" || row.tier === "1" ? "early" : "anytime",
      nextPickGuidance: needs.length > 0 ? { "ko-KR": needs } : { "ko-KR": ["manual_strategy_review"] },
      explanation: {
        compact: {
          "ko-KR": `웅이/Lumin BGA wtdPWR ${formatNumber(row.wtdPwr)} (${row.tier}) 기반의 우선 큐레이션 후보입니다.`
        }
      },
      sourceRefs: [WOONGI_SOURCE_REF],
      confidence: "stat_inferred",
      updatedAt: importDate
    });
  }

  return [...profilesByCardId.values()].sort((left, right) => left.cardId.localeCompare(right.cardId));
}

function inferConcreteRoles(row: WoongiRow): string[] {
  const text = `${row.officialName} ${row.arenaName} ${row.effectText} ${row.costRaw ?? ""}`;
  const roles: string[] = [];

  if (/(밭|쟁기|농지|씨 뿌리|씨뿌리|파종)/.test(text)) roles.push("field_engine");
  if (/(곡식|채소|작물|씨앗|종자)/.test(text)) roles.push("grain_supply");
  if (/(농지|밭|파종|씨 뿌리|씨뿌리)/.test(text)) roles.push("grain_seeds_action_upgrade");
  if (/(음식|먹여|화로|화덕|가마|빵|요리|구걸)/.test(text)) roles.push("food_support");
  if (/(빵 굽기|빵굽기|화로|화덕|가마)/.test(text)) roles.push("bake_bread_access");
  if (/(추가점수|점수 계산|점수를 계산)/.test(text)) roles.push("late_bonus_points");

  return uniqueStrings(roles);
}

function inferNeeds(row: WoongiRow, roles: string[]): string[] {
  const needs: string[] = [];
  if (roles.includes("field_engine")) needs.push("grain_supply", "food_engine");
  if (roles.includes("grain_supply")) needs.push("bake_bread_access", "food_engine");
  if (roles.includes("bake_bread_access")) needs.push("grain_supply");
  if (row.effectText.includes("[") || row.effectText.includes("라운드")) needs.push("risk_conditional");
  return uniqueStrings(needs);
}

function buildExistingNameIndex(translations: CardTranslation[]): Map<string, string> {
  const index = new Map<string, string>();

  for (const translation of translations) {
    const names = [
      translation.name,
      translation.officialName,
      translation.bgaName,
      ...translation.aliases
    ].filter((value): value is string => typeof value === "string" && value.trim() !== "");

    for (const name of names) {
      const key = normalizeName(name);
      if (!index.has(key)) index.set(key, translation.cardId);
    }
  }

  return index;
}

function buildPreviousRowMappingIndex(queue: CardIdMapQueue | null): Map<string, string> {
  const index = new Map<string, string>();
  if (queue === null) return index;

  for (const row of queue.rows) {
    index.set(rowKey(row), row.cardId);
  }

  return index;
}

function rowKey(
  row: Pick<WoongiRow, "sourceSheet" | "sourceRow" | "sourceNumber" | "arenaName" | "officialName">
): string {
  return [
    row.sourceSheet,
    row.sourceRow,
    row.sourceNumber,
    normalizeName(row.arenaName),
    normalizeName(row.officialName)
  ].join("|");
}

function readWorksheet(
  entries: Map<string, Buffer>,
  sharedStrings: string[],
  filePath: string
): Array<{ rowNumber: number; cells: SheetRow }> {
  const xml = readZipText(entries, filePath);
  const rows: Array<{ rowNumber: number; cells: SheetRow }> = [];

  for (const rowMatch of xml.matchAll(/<row\b[^>]*\br="(\d+)"[^>]*>[\s\S]*?<\/row>/g)) {
    const rowNumber = Number(rowMatch[1]);
    const rowXml = rowMatch[0];
    const cells: SheetRow = {};

    for (const cellMatch of rowXml.matchAll(/<c\b[^>]*\br="([A-Z]+\d+)"([^>]*)>([\s\S]*?)<\/c>/g)) {
      const reference = cellMatch[1] ?? "";
      const attributes = cellMatch[2] ?? "";
      const body = cellMatch[3] ?? "";
      const valueMatch = body.match(/<v>([\s\S]*?)<\/v>/);
      if (!valueMatch) continue;

      let value: CellValue = xmlUnescape(valueMatch[1] ?? "");
      if (attributes.includes('t="s"')) value = sharedStrings[Number(value)] ?? "";
      else if (/^-?\d+(?:\.\d+)?$/.test(value)) value = Number(value);

      cells[columnNumber(reference)] = value;
    }

    rows.push({ rowNumber, cells });
  }

  return rows;
}

function parseSharedStrings(xml: string): string[] {
  return [...xml.matchAll(/<si>([\s\S]*?)<\/si>/g)].map((match) => {
    const body = match[1] ?? "";
    const textParts = [...body.matchAll(/<t(?:\s[^>]*)?>([\s\S]*?)<\/t>/g)].map((textMatch) =>
      xmlUnescape(textMatch[1] ?? "")
    );
    return textParts.join("");
  });
}

function parseZipEntries(buffer: Buffer): Map<string, Buffer> {
  const endOfCentralDirectoryOffset = findEndOfCentralDirectory(buffer);
  const entryCount = buffer.readUInt16LE(endOfCentralDirectoryOffset + 10);
  let centralDirectoryOffset = buffer.readUInt32LE(endOfCentralDirectoryOffset + 16);
  const entries = new Map<string, Buffer>();

  for (let index = 0; index < entryCount; index += 1) {
    assert.equal(buffer.readUInt32LE(centralDirectoryOffset), 0x02014b50, "invalid ZIP central directory header");

    const compressionMethod = buffer.readUInt16LE(centralDirectoryOffset + 10);
    const compressedSize = buffer.readUInt32LE(centralDirectoryOffset + 20);
    const fileNameLength = buffer.readUInt16LE(centralDirectoryOffset + 28);
    const extraLength = buffer.readUInt16LE(centralDirectoryOffset + 30);
    const commentLength = buffer.readUInt16LE(centralDirectoryOffset + 32);
    const localHeaderOffset = buffer.readUInt32LE(centralDirectoryOffset + 42);
    const fileName = buffer
      .subarray(centralDirectoryOffset + 46, centralDirectoryOffset + 46 + fileNameLength)
      .toString("utf8")
      .replaceAll("\\", "/");

    const localFileNameLength = buffer.readUInt16LE(localHeaderOffset + 26);
    const localExtraLength = buffer.readUInt16LE(localHeaderOffset + 28);
    const dataOffset = localHeaderOffset + 30 + localFileNameLength + localExtraLength;
    const compressed = buffer.subarray(dataOffset, dataOffset + compressedSize);

    if (compressionMethod === 0) entries.set(fileName, compressed);
    else if (compressionMethod === 8) entries.set(fileName, inflateRawSync(compressed));
    else throw new Error(`Unsupported ZIP compression method ${compressionMethod} for ${fileName}.`);

    centralDirectoryOffset += 46 + fileNameLength + extraLength + commentLength;
  }

  return entries;
}

function findEndOfCentralDirectory(buffer: Buffer): number {
  for (let offset = buffer.length - 22; offset >= 0; offset -= 1) {
    if (buffer.readUInt32LE(offset) === 0x06054b50) return offset;
  }
  throw new Error("Could not find ZIP end of central directory.");
}

function readZipText(entries: Map<string, Buffer>, filePath: string): string {
  const entry = entries.get(filePath);
  if (!entry) throw new Error(`Missing XLSX entry: ${filePath}`);
  return entry.toString("utf8");
}

function compareCards(left: Card, right: Card): number {
  const typeOrder: Record<CardType, number> = {
    occupation: 0,
    minor_improvement: 1,
    major_improvement: 2
  };
  return typeOrder[left.type] - typeOrder[right.type] || left.id.localeCompare(right.id);
}

function proposedCardId(type: CardType, sourceNumber: number): string {
  const prefix =
    type === "occupation" ? "occ" : type === "minor_improvement" ? "minor" : "major";
  return `${prefix}-woongi-${String(sourceNumber).padStart(3, "0")}`;
}

function isGeneratedWoongiId(cardId: string): boolean {
  return /^(?:occ|minor|major)-woongi-\d{3}$/.test(cardId);
}

function normalizeCellText(value: CellValue | undefined): string {
  return typeof value === "string" || typeof value === "number"
    ? String(value).normalize("NFKC").trim().replace(/[ \t]+/g, " ")
    : "";
}

function normalizeEffectText(value: CellValue | undefined): string {
  return normalizeCellText(value).replace(/\r\n?/g, "\n");
}

function normalizeOptionalRaw(value: CellValue | undefined): string | undefined {
  const text = normalizeCellText(value);
  return text === "" || text === "-" ? undefined : text;
}

function normalizeTier(value: CellValue | undefined): string {
  return normalizeCellText(value) || "없음";
}

function isActiveTier(tier: string): boolean {
  return tier !== "없음";
}

function normalizeName(value: string): string {
  return value.normalize("NFKC").trim().replace(/\s+/g, " ").toLocaleLowerCase("ko-KR");
}

function toInteger(value: CellValue | undefined): number | undefined {
  const parsed = toNumber(value);
  return parsed === undefined ? undefined : Math.trunc(parsed);
}

function toNumber(value: CellValue | undefined): number | undefined {
  if (typeof value === "number" && Number.isFinite(value)) return value;
  if (typeof value !== "string") return undefined;
  const normalized = value.replace(/,/g, "").trim();
  if (!normalized) return undefined;
  const parsed = Number(normalized);
  return Number.isFinite(parsed) ? parsed : undefined;
}

function summarizeEffect(effectText: string): string {
  const normalized = effectText.replace(/^-+\s*/, "").replace(/\s+/g, " ").trim();
  if (normalized.length <= 120) return normalized;
  return `${normalized.slice(0, 117).trim()}...`;
}

function columnNumber(reference: string): number {
  const column = reference.match(/[A-Z]+/)?.[0];
  if (!column) throw new Error(`Invalid cell reference: ${reference}`);

  let result = 0;
  for (const character of column) {
    result = result * 26 + character.charCodeAt(0) - 64;
  }
  return result;
}

function xmlUnescape(value: string): string {
  return value
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&amp;/g, "&")
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'");
}

function uniqueStrings(values: string[]): string[] {
  return [...new Set(values.filter((value) => value.trim() !== ""))];
}

function formatNumber(value: number | undefined): string {
  return value === undefined ? "unknown" : String(Math.round(value * 100) / 100);
}

function parseCliOptions(args: string[]): CliOptions {
  const options: CliOptions = {
    write: false,
    inputPath: defaultInputPath
  };

  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index];
    if (arg === "--write") {
      options.write = true;
    } else if (arg === "--input") {
      const inputPath = args[index + 1];
      if (!inputPath) throw new Error("--input requires a path.");
      options.inputPath = inputPath;
      index += 1;
    } else if (arg === "--help" || arg === "-h") {
      printHelp();
      process.exit(0);
    } else {
      throw new Error(`Unknown argument: ${arg}`);
    }
  }

  return options;
}

function printHelp(): void {
  console.log(`Usage: node scripts/import-woongi-xlsx.ts [--write] [--input PATH]

Parses Woongi/bigman0603's Agricola tierlist spreadsheet and generates:
- data/normalized/cards.json
- data/normalized/translations.ko-KR.json
- data/normalized/stats.woongi-lumin-bga.2025-09-01.json
- data/normalized/card-pool.bga-arena.woongi-2025-09-01.json
- data/manual/card-id-map.woongi.2025-09-01.review.json
- data/manual/card-strategy-profiles.json seed profiles for high-WtdPWR cards`);
}

async function readJsonIfExists<T>(filePath: string, fallback: T): Promise<T> {
  try {
    return JSON.parse(await readFile(resolveWorkspacePath(filePath), "utf8")) as T;
  } catch (error) {
    if (isNodeErrnoException(error) && error.code === "ENOENT") return fallback;
    throw error;
  }
}

async function writeJson(filePath: string, value: unknown): Promise<void> {
  const absolutePath = resolveWorkspacePath(filePath);
  await mkdir(path.dirname(absolutePath), { recursive: true });
  await writeFile(absolutePath, `${JSON.stringify(value, null, 2)}\n`, "utf8");
}

function resolveWorkspacePath(filePath: string): string {
  return path.isAbsolute(filePath) ? filePath : path.join(rootDir, filePath);
}

function normalizePath(filePath: string): string {
  return filePath.replaceAll("\\", "/");
}

function isMainModule(): boolean {
  const scriptPath = process.argv[1];
  return scriptPath !== undefined && pathToFileURL(path.resolve(scriptPath)).href === import.meta.url;
}

function isNodeErrnoException(error: unknown): error is NodeJS.ErrnoException {
  return error instanceof Error && "code" in error;
}
