import assert from "node:assert/strict";
import {
  buildWoongiImport,
  WOONGI_CARD_POOL_PROFILE_ID,
  WOONGI_SOURCE_REF,
  WOONGI_STATS_SNAPSHOT_ID
} from "./import-woongi-xlsx.ts";

const output = await buildWoongiImport();

assert.equal(output.rows.length, 683);
assert.deepEqual(countBy(output.rows, (row) => row.cardType), {
  major_improvement: 10,
  minor_improvement: 337,
  occupation: 336
});

const beggingStudent = output.rows.find(
  (row) => row.sourceSheet === "occupations" && row.sourceNumber === 1
);
assert.ok(beggingStudent, "first occupation row should be parsed.");
assert.equal(beggingStudent.cardId, "occ-woongi-001");
assert.equal(beggingStudent.officialName, "\uad6c\uac78\ud558\ub294 \ud559\uc0dd");
assert.equal(beggingStudent.tier, "S");
assert.equal(beggingStudent.wtdPwr, 6.22);
assert.ok(beggingStudent.effectText.includes("\uad6c\uac78 \ub9c8\ucee4"));

const well = output.rows.find((row) => row.sourceSheet === "improvements" && row.sourceNumber === 249);
assert.ok(well, "major improvement rows should be parsed.");
assert.equal(well.cardId, "major-woongi-249");
assert.equal(well.cardType, "major_improvement");
assert.equal(well.officialName, "\uc6b0\ubb3c");
assert.equal(well.tier, "\uc8fc\uc694 \uc124\ube44");
assert.equal(well.costRaw, "3\ub3cc/1\ub098\ubb34");

const beggingStudentCard = output.cards.find((card) => card.id === beggingStudent.cardId);
assert.ok(beggingStudentCard, "normalized card should be generated.");
assert.equal(beggingStudentCard.type, "occupation");
assert.equal(beggingStudentCard.availability.bga, true);
assert.ok(beggingStudentCard.sourceRefs.includes(WOONGI_SOURCE_REF));

const beggingStudentTranslation = output.translations.find(
  (translation) => translation.cardId === beggingStudent.cardId
);
assert.ok(beggingStudentTranslation, "Korean translation should be generated.");
assert.equal(beggingStudentTranslation.name, "\uad6c\uac78\ud558\ub294 \ud559\uc0dd");
assert.ok(beggingStudentTranslation.effectText?.includes("\uad6c\uac78 \ub9c8\ucee4"));
assert.ok(beggingStudentTranslation.sourceRefs.includes(WOONGI_SOURCE_REF));

const beggingStudentStat = output.stats.find((stat) => stat.cardId === beggingStudent.cardId);
assert.ok(beggingStudentStat, "Woongi/Lumin BGA stat row should be generated.");
assert.equal(beggingStudentStat.snapshotId, WOONGI_STATS_SNAPSHOT_ID);
assert.equal(beggingStudentStat.rank, 1);
assert.equal(beggingStudentStat.tier, "S");
assert.equal(beggingStudentStat.wtdPwr, 6.22);

assert.equal(output.cardPoolProfile.id, WOONGI_CARD_POOL_PROFILE_ID);
assert.ok(output.cardPoolProfile.sourceRefs.includes(WOONGI_SOURCE_REF));
assert.equal(output.cardPoolProfile.cardStatuses[beggingStudent.cardId], "active");
assert.equal(output.cardPoolProfile.cardStatuses[well.cardId], "active");

assert.equal(output.cardIdMapQueue.sourceRef, WOONGI_SOURCE_REF);
assert.equal(output.cardIdMapQueue.snapshotId, WOONGI_STATS_SNAPSHOT_ID);
assert.equal(output.cardIdMapQueue.summary.totalRows, output.rows.length);
assert.equal(
  output.cardIdMapQueue.summary.matchedExisting + output.cardIdMapQueue.summary.autoGenerated,
  output.rows.length
);
assert.equal(new Set(output.cardIdMapQueue.rows.map((row) => row.cardId)).size, output.rows.length);

const beggingStudentProfile = output.strategyProfiles.find(
  (profile) => profile.cardId === beggingStudent.cardId
);
assert.ok(beggingStudentProfile, "top WtdPWR card should get a stat-inferred strategy profile.");
assert.equal(beggingStudentProfile.cardPoolProfileId, WOONGI_CARD_POOL_PROFILE_ID);
assert.equal(beggingStudentProfile.confidence, "stat_inferred");
assert.equal(beggingStudentProfile.isBroken, true);
assert.equal(beggingStudentProfile.isPlanAnchor, true);
assert.ok(beggingStudentProfile.roles.includes("broken"));
assert.ok(beggingStudentProfile.sourceRefs.includes(WOONGI_SOURCE_REF));
assert.ok(beggingStudentProfile.riskTags.includes("needs_manual_strategy_review"));

console.log("Woongi XLSX importer contract passed.");

function countBy<T>(values: T[], keyFor: (value: T) => string): Record<string, number> {
  return values.reduce<Record<string, number>>((counts, value) => {
    const key = keyFor(value);
    counts[key] = (counts[key] ?? 0) + 1;
    return counts;
  }, {});
}
